apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whack-a-pod
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 12
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/gogococo/whack_a_pod/api:master
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: whack-a-pod
  name: api
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: api