apiVersion: v1
kind: Namespace
metadata:
  name: whack-a-pod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: whack-a-pod
  name: ingress-wap
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8080
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game
            port:
              number: 8080